name: Build

on:
  push:
  workflow_dispatch:

jobs:
  call-windows-build:
    name: Windows Build
    uses: ./.github/workflows/win-build.yml
    
  call-windows-deploy:
    needs: call-windows-build
    name: Windows Deploy
    uses: ./.github/workflows/win-build.yml