name: Windows Build

on:
  workflow_call:

jobs:
  win-build:
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        repository: novusengine/Servers

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - name: Premake
      run: |
        premake5 vs2022

    - name: Build
      run: |
        msbuild /m /p:Configuration=Debug Build/Servers.sln
        
    - name: Upload Game Server artifact
      uses: actions/upload-artifact@v4
      with:
        name: Server-Game
        path: Build/Bin/Servers/Debug/Server-Game.exe

  win-deploy:
    needs: win-build
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
    
    steps:
    - name: Stop NovusServer service
      run: |
        net stop NovusServer
    
    - name: Download Game Server artifact
      uses: actions/download-artifact@v4
      with:
        name: Server-Game
        path: c:/server
    
    - name: Start NovusServer service
      run: |
        net stop NovusServer